// Code generated by "stringer -type=ClientMessageType"; DO NOT EDIT.

package rfb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SetPixelFormatMsgType-0]
	_ = x[SetEncodingsMsgType-2]
	_ = x[FramebufferUpdateRequestMsgType-3]
	_ = x[KeyEventMsgType-4]
	_ = x[PointerEventMsgType-5]
	_ = x[ClientCutTextMsgType-6]
	_ = x[AteniKVMKeyEventMsgType-4]
	_ = x[AteniKVMPointerEventMsgType-5]
}

const (
	_ClientMessageType_name_0 = "SetPixelFormatMsgType"
	_ClientMessageType_name_1 = "SetEncodingsMsgTypeFramebufferUpdateRequestMsgTypeKeyEventMsgTypePointerEventMsgTypeClientCutTextMsgType"
)

var (
	_ClientMessageType_index_1 = [...]uint8{0, 19, 50, 65, 84, 104}
)

func (i ClientMessageType) String() string {
	switch {
	case i == 0:
		return _ClientMessageType_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _ClientMessageType_name_1[_ClientMessageType_index_1[i]:_ClientMessageType_index_1[i+1]]
	default:
		return "ClientMessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
