// Code generated by "stringer -type=TightCompression"; DO NOT EDIT.

package rfb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TightCompressionBasic-0]
	_ = x[TightCompressionFill-8]
	_ = x[TightCompressionJPEG-9]
	_ = x[TightCompressionPNG-10]
}

const (
	_TightCompression_name_0 = "TightCompressionBasic"
	_TightCompression_name_1 = "TightCompressionFillTightCompressionJPEGTightCompressionPNG"
)

var (
	_TightCompression_index_1 = [...]uint8{0, 20, 40, 59}
)

func (i TightCompression) String() string {
	switch {
	case i == 0:
		return _TightCompression_name_0
	case 8 <= i && i <= 10:
		i -= 8
		return _TightCompression_name_1[_TightCompression_index_1[i]:_TightCompression_index_1[i+1]]
	default:
		return "TightCompression(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
